### ISSUE TITLE
Only a few of my Shared Queries are displayed in the Choose a Query drop down

### ISSUE THREAD

**Issue by heresandyboy** [Quadrotech/ADOScheduledWorkItemQuery#1]
Hi,

This looks really good, I'm just trying it out for the first time and having an issue. 
In the task editor, the dropdown for Choose a Query does not display all my queries.
I'm not sure if it is to do with folder depth. It's only showing older queries, nothing that I have created over the last week or so, all of the new Queries I have saved 4 folder levels deep under Shared Queries.

Hope you can help, and thanks for making this.

**Comment by MichelZ** [comment]
Hi

Thanks for the kind words. I think I found and fixed the issue, a new version should be available now. Can you try again?

Cheers
Michel

**Comment by heresandyboy** [comment]
Hi,

Thanks for the quick response. I have tried again this morning, unfortunately now there are no results found at all when clicking 'Choose a query'.

I subsequently deleted the build pipeline, removed and re-added the extension and tried again but the results are the same. 

![image](https://user-images.githubusercontent.com/553990/55717984-82a01e00-59f2-11e9-9050-657f84886c90.png)

**Comment by MichelZ** [comment]
Indeed...  It is not noted in the API Documentation, but it only allows to grab 2 levels deep of queries.
You can validate this by going to:
https://dev.azure.com/<organization>/<project>/_apis/wit/queries?api-version=5.0&$depth=3

You will get an error message saying: 

message | "A query parameter specified in the request URI is outside the permissible range: Parameter Name: depth, Acceptable Range: 0 to 2"

This <seems> to be some kind of Bug to me, as there doesn't seem to be a way to get the actual hierarchy.
I'll try to raise this with Microsoft, and correct the code down to 2 again ASAP

**Comment by MichelZ** [comment]
The Task should now show 2 levels again.

A few more investigations now:
- It is possible to get more levels using multiple queries. Unfortunately this is not easy to do in the model they have.
- It is possible to search for queries it seems

I will add the following features:
- Provide your own ID, so you can find out the query ID on your own and just provide it to the Task
- Add search functionality to the task so you can easily search for the query that you need

In the meantime, the best option is probably to create a new folder "Scheduled Queries" or something in the Root, and then placing your queries there. 
I hope to be able to enhance the task in the next couple of weeks

**Comment by patilsv28** [comment]
Hi @heresandyboy  @MichelZ  Could you please help how to use this extension to schedule emails?

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
