### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by daismith** [Quadrotech/ADOScheduledWorkItemQuery#10]
Currently the queries are ordered in a different way to that set up within the email. By default the email appears to be ordered by System.Id.

Is it possible to make a modification to allow the user to dictate how the queries are ordered.

Many thanks

**Comment by MichelZ** [comment]
So you have a query that you have saved in Azure DevOps, and you have set a sort-ordering on it, and the e-mail gets sent in the wrong order?

I'll check if I can do something about this

**Comment by daismith** [comment]
Many thanks for getting back. Yes, that is correct. In my case, the queries within Devops are set up to be ordered by the person the items are assigned to, but get reordered by ID in the email that is sent.

Kind regards

Dave

**Comment by MichelZ** [comment]
This should work now, please re-open if not

**Comment by daismith** [comment]
Hi, I’m now getting the error below.

1 error(s), 0 warning(s)
[https://cdn.vsassets.io/content/notifications/icon-failure.png]
a.fields[referenceName].localeCompare is not a function

Many thanks

Dave

**Comment by MichelZ** [comment]
Thanks, looking into this now

**Comment by MichelZ** [comment]
Just updated the extension again. Would you mind trying it out one more time @daismith ? Thanks for the help!

**Comment by daismith** [comment]
Thankyou Michel,

It works perfectly.

Dave
