### ISSUE TITLE
Silent failure on "Work items and direct links" type queries

### ISSUE THREAD

**Issue by bbantahm** [Quadrotech/ADOScheduledWorkItemQuery#11]
After spending a lot of time trying to debug why this wasn't working (mostly focusing on the SMTP side), I finally thought of the potential problem with the query type.  I have several "Flat list of items" shared queries and a few "Work items and direct links" type queries. All queries show up as available choices under "Choose a Query", but only the flat list queries get processed and sent as an email.

If I open the shared query for the ones with direct links and select "Email query" from within DevOps, it emails the results with linked items just fine.

**Comment by MichelZ** [comment]
I've just pushed a first version which should support this scenario. Would you mind trying it out? @bbantahm  @kumarkaran1 @philcarbone

Thanks!

**Comment by philcarbone** [comment]
I'm trying it out now

**Comment by philcarbone** [comment]
It is working well with a "Tree of work items". Thanks!

**Comment by MichelZ** [comment]
Wonderful, thanks. Closing this then :)
