### ISSUE TITLE
Send Query Result as E-Mail

### ISSUE THREAD

**Issue by kumarkaran1** [Quadrotech/ADOScheduledWorkItemQuery#12]
Send Query Result as E-Mail  works really well with just one caveat that took me forever to debug. It will NOT work with queries of the type "Work items and direct links". It looks like everything is fine, the task runs and everything is successful but no email is ever sent. With a query of type "Flat list of work items" the results from the build pipeline task looks the same but the email is sent with the query results.

**Comment by MichelZ** [comment]
Duplicate #11
