### ISSUE TITLE
None of My Queries are showing up in the My Query ID Dropdown

### ISSUE THREAD

**Issue by jzambo49** [Quadrotech/ADOScheduledWorkItemQuery#13]
Hi,
I downloaded the extension and made a new Javascript build pipeline 
<img width="955" alt="Javascript Pipeline" src="https://user-images.githubusercontent.com/62142842/76766146-8c371780-6765-11ea-8488-417642f79e90.PNG">

A new SMTP Server Service Connection
<img width="526" alt="SMTP Connection" src="https://user-images.githubusercontent.com/62142842/76766235-ab35a980-6765-11ea-9745-2f13722193fa.PNG">

And a new Azure Repos/Team Foundation Server Service Connection
<img width="516" alt="Azure Repos Service Connection" src="https://user-images.githubusercontent.com/62142842/76766324-cf918600-6765-11ea-9e98-536684ac1077.PNG">

And when I try to create the Scheduled Work Item Query task in my pipeline, none of My Queries are showing up in the My Query ID drop down. It says "No Queries Found." 

Am I doing something wrong? For the Azure Repos service connection I tried making the Connection URL the organization URL, the URL of the specific project My Queries are in, and the URL of the Queries page.
For the SMTP service connection, I tried making the SMTP Server Port 25, 587, 2525, 465, and 25025. After changing them, I did hard refreshes on Azure. 

The My Query ID drop down was blank with everything I tried. Please help. Thanks!

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
