### ISSUE TITLE
SMTP connections empty?

### ISSUE THREAD

**Issue by ashwinifly** [Quadrotech/ADOScheduledWorkItemQuery#15]
Why do I see my SMTP connections always empty? (See attached image)
![image](https://user-images.githubusercontent.com/6550276/78941400-779c2580-7a6c-11ea-8d7b-77eb15a1d53a.png)

How does the task query for list of SMTP connections? do I need to configure this somewhere in my DevOps account?

**Comment by ashwinifly** [comment]
@MichelZ ?

**Comment by ashwinifly** [comment]
Was able to add a new connection in service connections

**Comment by umairgillani94** [comment]
@ashwinifly Can you please share the steps how did you do that?
