### ISSUE TITLE
URL in email does not direct to project

### ISSUE THREAD

**Issue by jlad00** [Quadrotech/ADOScheduledWorkItemQuery#17]
The query URL generated in the email coming from the extention does not link to the query and project specified in the task settings. It links to a project "web" which is non-existent in our Collection so it results in a dead browser link for the recipient . We are running ADO 2019 update 1, On Prem. 

Thanks in advance for any insights you might have. 

![ado](https://user-images.githubusercontent.com/12310817/84552152-a6c95000-acc4-11ea-8049-0909f9449c06.png)

**Comment by Tuba-guy** [comment]
The links not working is a show stopper for me.  Very little point in sharing a query that should link to DevOps when the links don't work.  

If I open the query in DevOps/Queries and Choose "Email Query"  the links work. So there is something going on when the query is run with the Scheduled Work Item Query task.

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
