### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by lealcrf** [Quadrotech/ADOScheduledWorkItemQuery#18]
I configured the build task to use our internal smtp server, the same used by azure devops server itself. I can find the exactly query I want to email but when the build runs it fails with the message "unable to verify the first certificate" no matter the TLS configuration I use for the connection.

How can I fix this?

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
