### ISSUE TITLE
Unable to use the extension Scheduled Work Item Query

### ISSUE THREAD

**Issue by Asifvirani** [Quadrotech/ADOScheduledWorkItemQuery#19]
Already installed but Unable to use the extension Scheduled Work Item Query. How do I use it? I need a query to run and send me the results automatically

**Comment by umairgillani94** [comment]
Facing the same issue. Can anyone share steps to use this extension?

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
