### ISSUE TITLE
Feature Request: Only send when there are query results

### ISSUE THREAD

**Issue by Rarefy-Dev** [Quadrotech/ADOScheduledWorkItemQuery#2]
Hello,
Everything is working great for us.  Would like to request a feature that would only send the email if the query that is run has 1 or more returned rows.

Cheers,
Mark

**Comment by MichelZ** [comment]
Thanks for the suggestion, this feature should now be available in the latest version with a checkbox to send empty mails (default: true), you should be able to simply uncheck this
