### ISSUE TITLE
##[error]Cannot read property 'queryResultType' of null

### ISSUE THREAD

**Issue by stuartrainsworth** [Quadrotech/ADOScheduledWorkItemQuery#22]
Struggling to find where this property is not being carried over; the query is a standard one which returns a flat list of work items.  I've tried changing it to a tree, and both return this error.

**Comment by imaginariuss** [comment]
Hi @stuartrainsworth ! Have you fount the root cause/solution?

**Comment by stuartrainsworth** [comment]
Sorry, no. I ended up replicating this functionality using an Azure Logic App instead.
