### ISSUE TITLE
Unable to use this extension in Azure DevOps

### ISSUE THREAD

**Issue by Patsjaju** [Quadrotech/ADOScheduledWorkItemQuery#25]
I use Azure DevOps for managing my projects and want to schedule and email my query results to my team. I do not use pipelines. I have enabled it within my project but not sure how to set it up. Can someone help me with how to set the extension so that I can start using it.

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
