### ISSUE TITLE
End point not present

### ISSUE THREAD

**Issue by umairgillani94** [Quadrotech/ADOScheduledWorkItemQuery#26]
I am using shared query but it is still throwing end point error which is needed only for my private queries as per docs.

#[debug]Evaluating condition for step: 'ADOScheduledWorkItemQuery'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: ADOScheduledWorkItemQuery
==============================================================================
Task         : Scheduled Work Item Query
Description  : Sends an E-Mail on a Schedule for Work Item Queries
Version      : 0.89.0
Author       : Quadrotech Solutions AG
Help         : https://github.com/Quadrotech/ADOScheduledWorkItemQuery
==============================================================================
##[debug]Using node path: /home/vsts/agents/2.187.2/externals/node/bin/node
##[debug]agent.TempDirectory=/home/vsts/work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_SENDMETHOD
##[debug]loading INPUT_CONNECTEDSERVICENAMESMTP
##[debug]loading INPUT_PROJECT
##[debug]loading INPUT_QUERYTYPE
##[debug]loading INPUT_QUERY
##[debug]loading INPUT_SENDIFEMPTY
##[debug]loading INPUT_SUBJECT
##[debug]loading INPUT_EMAILADDRESSES
##[debug]loading ENDPOINT_AUTH_52a234ee-67ae-4fd4-a12a-2986a62cffd1
##[debug]loading ENDPOINT_AUTH_SCHEME_52a234ee-67ae-4fd4-a12a-2986a62cffd1
##[debug]loading ENDPOINT_AUTH_PARAMETER_52a234ee-67ae-4fd4-a12a-2986a62cffd1_SMTPSERVERNOAUTH
##[debug]loading ENDPOINT_AUTH_PARAMETER_52a234ee-67ae-4fd4-a12a-2986a62cffd1_SMTPPORTNOAUTH
##[debug]loading ENDPOINT_AUTH_PARAMETER_52a234ee-67ae-4fd4-a12a-2986a62cffd1_TLSOPTIONSNOAUTH
##[debug]loading ENDPOINT_AUTH_PARAMETER_52a234ee-67ae-4fd4-a12a-2986a62cffd1_SMTPFROMEMAILNOAUTH
##[debug]loading ENDPOINT_AUTH_PARAMETER_52a234ee-67ae-4fd4-a12a-2986a62cffd1_SMTPFROMNAMENOAUTH
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 19
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]queryType=Shared
##[debug]task result: Failed
##[error]Endpoint not present: SystemVssConnection
##[debug]Processed: ##vso[task.issue type=error;]Endpoint not present: SystemVssConnection
##[debug]Processed: ##vso[task.complete result=Failed;]Endpoint not present: SystemVssConnection
Finishing: ADOScheduledWorkItemQuery

**Comment by waldyhester** [comment]
Does not work on linux (guessing).

I had the same error and I changed the agent to "windows-2019" and worked.

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
