### ISSUE TITLE
"Send e-mail on empty result" option does not work for hierarchical queries

### ISSUE THREAD

**Issue by aroje** [Quadrotech/ADOScheduledWorkItemQuery#27]
When a hierarchical query (tree or direct link) returns no results and the "Send e-mail on empty result" is unchecked, then the email is still sent.

**Comment by HEMANTHSHANKAR** [comment]
Azure DevOps server or Azure DevOps Service ?

**Comment by aroje** [comment]
Azure DevOps Service

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
