### ISSUE TITLE
Send email with wrong hyperlink

### ISSUE THREAD

**Issue by Chodipalli** [Quadrotech/ADOScheduledWorkItemQuery#29]
When we click on System Id from the results, its not redirecting to the results board, It says **Page Not Found**. Is there a way that i can resolve this issue

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
