### ISSUE TITLE
Dates that are attached to the email

### ISSUE THREAD

**Issue by CS10-85** [Quadrotech/ADOScheduledWorkItemQuery#4]
Hi there.
Great plugin! Just successfully implemented it this morning.

I appreciate this may not be an issue with the plugin but thought I would check.

My query includes a date field but the dates are returned like this: 2018-12-14T11:52:35.7Z

Whereas in the query results via devops, they are returned as: 14-12-18 11:52

How can I alter what is emailed to be the same as the query results?

Thanks in advance,
Craig

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
