### ISSUE TITLE
200 Work Item limit

### ISSUE THREAD

**Issue by CS10-85** [Quadrotech/ADOScheduledWorkItemQuery#5]
Hi there,
My build failed last night with the following reason:

VS403474: You requested 203 work items which exceeds the limit of 200

Is this limit of 200 set by this extension or within my settings in DevOps?

Thanks,
Craig

**Comment by MichelZ** [comment]
This is a limit of the code. Will fix

**Comment by MichelZ** [comment]
This should be resolved now. Please re-open if not
