### ISSUE TITLE
Custom Fields added to Shared Query

### ISSUE THREAD

**Issue by surajraja** [Quadrotech/ADOScheduledWorkItemQuery#6]
When we add custom fields to the shared query, email link sent is having the wrong address 

https://vsrm.dev.azure.com/ instead of https://dev.azure.com/

**Comment by DToTheCdel** [comment]
Same issue here.
How do we get rid of the `vsrm` string in the url ?

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
