### ISSUE TITLE
Not All Project are showing

### ISSUE THREAD

**Issue by eyacoub** [Quadrotech/ADOScheduledWorkItemQuery#9]
Hello,

I was trying to create a new job to send email from a specific project, but unfortunately the Project is not showing in the list of Projects, is there any specific steps that needs to be done to show all the projects?

Thank you.

**Comment by eyacoub** [comment]
after checking it again, i noticed that all the project that we have applied a customization on the process is not showing. hope this can help.

**Comment by MichelZ** [comment]
This is weird. 
The code uses this endpoint:
{{endpoint.url}}/_apis/projects?api-version=5.0
https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-5.0

> Get all projects in the organization that the authenticated user has access to.

Can you try that endpoint and see if you get all the projects you need?

**Comment by MichelZ** [comment]
Here is the successor to this task, as I am not working at the publisher company anymore:
https://marketplace.visualstudio.com/items?itemName=TechFreak.TFADOScheduledWorkItemQuery
